---
- name: unconfigure_cluster | unconfiguring galera cluster (Debian)
  file:
    path: "/etc/mysql/conf.d/galera.cnf"
    state: "absent"
  become: true
  when: ansible_os_family == "Debian"

- name: unconfigure_cluster | unconfiguring galera cluster
  file:
    path: "/etc/galera_cluster_configured"
    state: "absent"
  become: true

- name: unconfigure_cluster | restarting mysql when reconfiguring galera cluster
  service:
    name: "mysql"
    state: "restarted"
  become: true
